<a href="https://colab.research.google.com/github/azeem932356/Numpy-Pandas-OpenCV-DataVisualization-DataScraping/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

short form of Numerical Python

Numpy is written in c

NumPy is originally designed for **CPU** Memory {CPU: Central Processing Unit} and Numpy can't run on **GPU** {GPU has its own Memory called **VRAM**}


In [2]:
#Vectors and Matrices
#Vector is a list of numbers {You can call as 1D Vectors}    --> single digit is called scaler
#Matrics are List of List {You can call as 2D Vectors}

In [3]:
import numpy as np

In [4]:
python_list = [1, 2, 3, 4, 5, -5]
python_list

[1, 2, 3, 4, 5, -5]

In [5]:
#converting a list into a vector
np.array(python_list)

array([ 1,  2,  3,  4,  5, -5])

In [6]:
#checking Dimensions and Shape
numpy_arry = np.array(python_list)
numpy_arry.shape

(6,)

In [7]:
#Dimension
len(numpy_arry.shape)

1

In [8]:
#list of list {2D} Matrix
python_list_list = [[1, 2], [3, 4]]
python_list_list1= np.array(python_list_list)
python_list_list1

array([[1, 2],
       [3, 4]])

In [9]:
python_list_list1.shape

(2, 2)

In [10]:
len(python_list_list1)

2

In [11]:
#Creating list using range()

list(range(5))

[0, 1, 2, 3, 4]

In [12]:
#now using arrange {similar to range function}
np.arange(4)


array([0, 1, 2, 3])

In [13]:
#making shapes zeros and specifying the for 2D zeros(rows, columns)
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [14]:
#zeros for higher dimensions zeros(depth, rows, columns)
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
#you can also do with 1
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [16]:
#using random()

#decimals
np.random.random((2, 2))

array([[0.88950636, 0.61866276],
       [0.16185219, 0.32114203]])

In [17]:
#integers
np.random.randint(1, 10, (2, 3))


array([[3, 1, 1],
       [7, 4, 7]])

In [18]:
#one random integer from(0, 1, 2 3is excluded)
np.random.randint(3)

1

In [19]:
#random size matix
np.random.randint(5, size=(2, 2))

array([[2, 3],
       [2, 3]])

**Data Types - NumPy**


**int** - int8, int16, int36, int64    --> Integers

**uint** - uint8, uint16, uint36, uint64   --> unsigned (nonnegative) integers

**bool** - Bool  --> Boolean (T or F)

**float** - float16, float36, float64, float128   --> floating point numbers

**complex**  - complex64, complex128, complex256    --> complex valued floating-point numbers

**Type**	| **Bits**  | 	**Bytes**	 | **Range**

int8 -->  8 -->    1	-->    -128 to 127

int16	 -->   16	 -->   2	   -->  -32,768 to 32,767

int32	 -->  32	 -->  4	   -->  -2.1 billion to 2.1 billion

int64	 -->  64	-->   8	    -->  ±9.2 quintillion

In [20]:
a = [1, 2, 3, 4]
arr =np.array(a)
arr

array([1, 2, 3, 4])

In [21]:
#to check a data-type
arr.dtype

dtype('int64')

In [22]:
#converting a datatype
b= [1, 2, 3, 4]
arry= np.array(b, dtype= np.int64)
arry.dtype

dtype('int64')

In [23]:
#floating point
a= [1.2, 3.4, 5]
type(a[-1])

int

If you create a NumPy array with mixed data types, NumPy will try to make all elements the same type because NumPy arrays are **homogeneous** (all elements have **one dtype**).

In [24]:
a= np.array([1, 2, 3, "Hello"])  #NumPy array converts all into one data type
print(a)
print(a.dtype)

['1' '2' '3' 'Hello']
<U21


In [25]:
#converting into Integer
a = np.array([1.7, 2.9, 3.1])

b = a.astype(int)

print(b)
print(b.dtype)

[1 2 3]
int64


In [26]:
# a.astype(np.int32).dtype
#                              } ---> explicitly use
 #a.astype(np.int64).dtype

converting to integer truncates the decimal part; it does not **round**

1.7 → 1

2.9 → 2

3.1 → 3

#NumPy - **Slicing**

array[start : stop : step] --> for 1D

arry[rows, columns] --> for 2D

arry[matrix, row, column] ---> for 3D (Tensor)

arry[batch, matrix, row, column]  --> for 4D(Tensor)

**1D** array

In [27]:
a = np.array([10, 20, 30, 40, 50, 60])  #1D

In [28]:
a.shape

(6,)

In [29]:
#for finding dimensions
len(a.shape)

1

In [30]:
#Elements from index 1 to 3
a[1:4]

array([20, 30, 40])

In [31]:
#for single element
a[0]     #--> in 1D array you can access any element by index

np.int64(10)

In [32]:
#you can also use steps also
a[0: 6: 2]

array([10, 30, 50])

**2D** array

arrary[rows, columns]

In [33]:
c= np.random.rand(5, 5) #it give you flot from 0 - 1

In [34]:
c

array([[0.07929599, 0.2474378 , 0.96520649, 0.97470204, 0.37229588],
       [0.18577129, 0.86437124, 0.3979493 , 0.32699384, 0.46752569],
       [0.98183601, 0.65674918, 0.08755111, 0.53090828, 0.73246144],
       [0.77730968, 0.16087377, 0.8746706 , 0.11886865, 0.85842223],
       [0.62751094, 0.78079889, 0.8144166 , 0.12974354, 0.27363775]])

In [35]:
d= np.random.randint(5, size=(5, 5))   #it gives you random numbers from 0 - 4 in the shape of (5, 5)

In [36]:
d

array([[0, 0, 2, 1, 4],
       [4, 4, 4, 1, 4],
       [4, 3, 1, 1, 1],
       [3, 2, 0, 4, 4],
       [1, 0, 1, 3, 1]])

In [37]:
d.shape

(5, 5)

In [38]:
len(d.shape)

2

In [39]:
#accessing single element in 2D --> i want first row(0) last element
d[0, 4]

np.int64(4)

In [55]:
#for entire row
d[0,]

array([0, 0, 2, 1, 4])

In [60]:
#first 2 rows
d[0:2, :]

array([[0, 0, 2, 1, 4],
       [4, 4, 4, 1, 4]])

In [57]:
#for last row
d[-1]

array([1, 0, 1, 3, 1])

In [59]:
#entire column
d[:, 4]  #--> read it as rows   ,column

array([4, 4, 1, 4, 1])

In [62]:
#for portion of a 2d
d[0:2, 3:5]

array([[1, 4],
       [1, 4]])

**3D** Array (Tensor)

array[matrix, row, column]

In [64]:
e= np.random.randint(5, size=(2, 3, 4))

In [65]:
e

array([[[1, 1, 4, 4],
        [4, 4, 3, 4],
        [1, 4, 3, 3]],

       [[0, 0, 2, 3],
        [3, 4, 4, 0],
        [3, 3, 4, 2]]])

In [68]:
#shape
e.shape

(2, 3, 4)

In [69]:
#finding Dimension
len(e.shape)

3

In [70]:
#one element
e[0, 1, 2]

np.int64(3)

In [71]:
#entire row
e[0, 1]

array([4, 4, 3, 4])

In [72]:
#first matrix
e[0]

array([[1, 1, 4, 4],
       [4, 4, 3, 4],
       [1, 4, 3, 3]])

In [40]:
#using random to generate
arr = np.random.rand(5, 5)
arr

array([[0.73134946, 0.30701074, 0.5834918 , 0.97794859, 0.25057556],
       [0.06332845, 0.30241523, 0.34317172, 0.72542971, 0.78912731],
       [0.77414322, 0.71471344, 0.60375763, 0.27629922, 0.35842107],
       [0.542126  , 0.87762373, 0.74961347, 0.77358294, 0.46608946],
       [0.24458325, 0.37506247, 0.29127928, 0.8708707 , 0.32106151]])

In [41]:
arr.shape

(5, 5)

In [42]:
arr.dtype

dtype('float64')

In [43]:
b = np.random.random((5, 5))
b

array([[0.8959662 , 0.94281777, 0.6259593 , 0.69035995, 0.69519429],
       [0.44375441, 0.11306757, 0.53792813, 0.77355457, 0.07871167],
       [0.35901798, 0.23445613, 0.51176553, 0.65348521, 0.3501195 ],
       [0.45791647, 0.57676543, 0.57379653, 0.04360465, 0.72725139],
       [0.54152161, 0.28830538, 0.82888005, 0.00376514, 0.9980348 ]])

In [44]:
b.shape

(5, 5)

In [45]:
b.dtype

dtype('float64')

In [46]:
len(b.shape)

2

In [47]:
b[1:3]

array([[0.44375441, 0.11306757, 0.53792813, 0.77355457, 0.07871167],
       [0.35901798, 0.23445613, 0.51176553, 0.65348521, 0.3501195 ]])

In [48]:
#working with comparison operators
arr_int = np.random.randint(5, size=(6, 5))

In [49]:
arr_int

array([[2, 1, 0, 4, 4],
       [2, 4, 3, 4, 4],
       [0, 3, 4, 2, 0],
       [1, 4, 4, 4, 3],
       [2, 1, 1, 1, 4],
       [0, 4, 1, 3, 0]])

In [50]:
arr_int0 =arr_int[0] #taking only first row

In [51]:
arr_int0

array([2, 1, 0, 4, 4])

In [52]:
arr_int0 == 0 #comparing in this row we have 0 or not and

array([False, False,  True, False, False])

In [53]:
arr_int0

array([2, 1, 0, 4, 4])

In [54]:
(arr_int0 == 0) | (arr_int0 == 1) | (arr_int0 == 2) #checking for if there any numbers like 0, 1, 2 {" | " is working as or operator}

array([ True,  True,  True, False, False])