<a href="https://colab.research.google.com/github/azeem932356/Numpy-Pandas-OpenCV-DataVisualization-DataScraping/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

short form of Numerical Python

Numpy is written in c

NumPy is originally designed for **CPU** Memory {CPU: Central Processing Unit} and Numpy can't run on **GPU** {GPU has its own Memory called **VRAM**}


In [ ]:
#Vectors and Matrices
#Vector is a list of numbers {You can call as 1D Vectors}    --> single digit is called scaler
#Matrics are List of List {You can call as 2D Vectors}

In [3]:
import numpy as np

In [2]:
python_list = [1, 2, 3, 4, 5, -5]
python_list

[1, 2, 3, 4, 5, -5]

In [4]:
#converting a list into a vector
np.array(python_list)

array([ 1,  2,  3,  4,  5, -5])

In [7]:
#checking Dimensions and Shape
numpy_arry = np.array(python_list)
numpy_arry.shape

1

In [8]:
#Dimension
len(numpy_arry.shape)

1

In [5]:
#list of list {2D} Matrix
python_list_list = [[1, 2], [3, 4]]
python_list_list1= np.array(python_list_list)
python_list_list1

array([[1, 2],
       [3, 4]])

In [6]:
python_list_list1.shape

(2, 2)

In [7]:
len(python_list_list1)

2

In [8]:
#Creating list using range()

list(range(5))

[0, 1, 2, 3, 4]

In [9]:
#now using arrange {similar to range function}
np.arange(4)


array([0, 1, 2, 3])

In [10]:
#making shapes zeros and specifying the for 2D zeros(rows, columns)
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [11]:
#zeros for higher dimensions zeros(depth, rows, columns)
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
#you can also do with 1
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [14]:
#using random()

#decimals
np.random.random((2, 2))

array([[0.58234885, 0.64030641],
       [0.1912564 , 0.06684227]])

In [15]:
#integers
np.random.randint(1, 10, (2, 3))


array([[4, 6, 3],
       [6, 6, 1]])

In [19]:
#one random integer from(0, 1, 2 3is excluded)
np.random.randint(3)

0

In [23]:
#random size matix
np.random.randint(5, size=(2, 2))

array([[4, 2],
       [2, 1]])