<a href="https://colab.research.google.com/github/azeem932356/Numpy-Pandas-OpenCV-DataVisualization-DataScraping/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

short form of Numerical Python

Numpy is written in c

NumPy is originally designed for **CPU** Memory {CPU: Central Processing Unit} and Numpy can't run on **GPU** {GPU has its own Memory called **VRAM**}


In [1]:
#Vectors and Matrices
#Vector is a list of numbers {You can call as 1D Vectors}    --> single digit is called scaler
#Matrics are List of List {You can call as 2D Vectors}

In [2]:
import numpy as np

In [3]:
python_list = [1, 2, 3, 4, 5, -5]
python_list

[1, 2, 3, 4, 5, -5]

In [4]:
#converting a list into a vector
np.array(python_list)

array([ 1,  2,  3,  4,  5, -5])

In [5]:
#checking Dimensions and Shape
numpy_arry = np.array(python_list)
numpy_arry.shape

(6,)

In [6]:
#Dimension
len(numpy_arry.shape)

1

In [7]:
#list of list {2D} Matrix
python_list_list = [[1, 2], [3, 4]]
python_list_list1= np.array(python_list_list)
python_list_list1

array([[1, 2],
       [3, 4]])

In [8]:
python_list_list1.shape

(2, 2)

In [9]:
len(python_list_list1)

2

In [10]:
#Creating list using range()

list(range(5))

[0, 1, 2, 3, 4]

In [11]:
#now using arrange {similar to range function}
np.arange(4)


array([0, 1, 2, 3])

In [12]:
#making shapes zeros and specifying the for 2D zeros(rows, columns)
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [13]:
#zeros for higher dimensions zeros(depth, rows, columns)
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
#you can also do with 1
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [15]:
#using random()

#decimals
np.random.random((2, 2))

array([[0.44728084, 0.98173105],
       [0.28303409, 0.50314925]])

In [16]:
#integers
np.random.randint(1, 10, (2, 3))


array([[7, 4, 8],
       [7, 7, 9]])

In [17]:
#one random integer from(0, 1, 2 3is excluded)
np.random.randint(3)

1

In [18]:
#random size matix
np.random.randint(5, size=(2, 2))

array([[2, 0],
       [0, 2]])

**Data Types - NumPy**


**int** - int8, int16, int36, int64    --> Integers

**uint** - uint8, uint16, uint36, uint64   --> unsigned (nonnegative) integers

**bool** - Bool  --> Boolean (T or F)

**float** - float16, float36, float64, float128   --> floating point numbers

**complex**  - complex64, complex128, complex256    --> complex valued floating-point numbers

**Type**	| **Bits**  | 	**Bytes**	 | **Range**

int8 -->  8 -->    1	-->    -128 to 127

int16	 -->   16	 -->   2	   -->  -32,768 to 32,767

int32	 -->  32	 -->  4	   -->  -2.1 billion to 2.1 billion

int64	 -->  64	-->   8	    -->  ±9.2 quintillion

In [19]:
a = [1, 2, 3, 4]
arr =np.array(a)
arr

array([1, 2, 3, 4])

In [20]:
#to check a data-type
arr.dtype

dtype('int64')

In [21]:
#converting a datatype
b= [1, 2, 3, 4]
arry= np.array(b, dtype= np.int64)
arry.dtype

dtype('int64')

In [22]:
#floating point
a= [1.2, 3.4, 5]
type(a[-1])

int

If you create a NumPy array with mixed data types, NumPy will try to make all elements the same type because NumPy arrays are **homogeneous** (all elements have **one dtype**).

In [23]:
a= np.array([1, 2, 3, "Hello"])  #NumPy array converts all into one data type
print(a)
print(a.dtype)

['1' '2' '3' 'Hello']
<U21


In [24]:
#converting into Integer
a = np.array([1.7, 2.9, 3.1])

b = a.astype(int)

print(b)
print(b.dtype)

[1 2 3]
int64


In [25]:
# a.astype(np.int32).dtype
#                              } ---> explicitly use
 #a.astype(np.int64).dtype

converting to integer truncates the decimal part; it does not **round**

1.7 → 1

2.9 → 2

3.1 → 3

#NumPy - **Slicing**

array[start : stop : step] --> for 1D

arry[rows, columns] --> for 2D

arry[matrix, row, column] ---> for 3D (Tensor)

arry[batch, matrix, row, column]  --> for 4D(Tensor)

**1D** array

In [26]:
a = np.array([10, 20, 30, 40, 50, 60])  #1D

In [27]:
a.shape

(6,)

In [28]:
#for finding dimensions
len(a.shape)

1

In [29]:
#Elements from index 1 to 3
a[1:4]

array([20, 30, 40])

In [30]:
#for single element
a[0]     #--> in 1D array you can access any element by index

np.int64(10)

In [31]:
#you can also use steps also
a[0: 6: 2]

array([10, 30, 50])

**2D** array

arrary[rows, columns]

In [32]:
c= np.random.rand(5, 5) #it give you flot from 0 - 1

In [33]:
c

array([[0.11908764, 0.18858022, 0.64370453, 0.35052744, 0.54413035],
       [0.00974337, 0.6387144 , 0.16547901, 0.70824713, 0.97008221],
       [0.42142916, 0.94058386, 0.34576758, 0.24644696, 0.80272764],
       [0.63754757, 0.19914627, 0.70252576, 0.40120423, 0.29485735],
       [0.69348787, 0.31989245, 0.56832758, 0.14679697, 0.89767755]])

In [34]:
d= np.random.randint(5, size=(5, 5))   #it gives you random numbers from 0 - 4 in the shape of (5, 5)

In [35]:
d

array([[2, 4, 1, 3, 0],
       [4, 4, 2, 0, 3],
       [3, 0, 3, 2, 4],
       [3, 3, 4, 3, 0],
       [2, 0, 0, 3, 4]])

In [36]:
d.shape

(5, 5)

In [37]:
len(d.shape)

2

In [38]:
#accessing single element in 2D --> i want first row(0) last element
d[0, 4]

np.int64(0)

In [39]:
#for entire row
d[0,]

array([2, 4, 1, 3, 0])

In [40]:
#first 2 rows
d[0:2, :]

array([[2, 4, 1, 3, 0],
       [4, 4, 2, 0, 3]])

In [41]:
#for last row
d[-1]

array([2, 0, 0, 3, 4])

In [42]:
#entire column
d[:, 4]  #--> read it as rows   ,column

array([0, 3, 4, 0, 4])

In [43]:
#for portion of a 2d
d[0:2, 3:5]

array([[3, 0],
       [0, 3]])

**3D** Array (Tensor)

array[matrix, row, column]

In [44]:
e= np.random.randint(5, size=(2, 3, 4))

In [45]:
e

array([[[0, 3, 2, 1],
        [3, 4, 0, 3],
        [2, 3, 3, 0]],

       [[2, 3, 0, 1],
        [4, 2, 2, 4],
        [4, 4, 3, 1]]])

In [46]:
#shape
e.shape

(2, 3, 4)

In [47]:
#finding Dimension
len(e.shape)

3

In [48]:
#one element
e[0, 1, 2]

np.int64(0)

In [49]:
#entire row
e[0, 1]

array([3, 4, 0, 3])

In [50]:
#first matrix
e[0]

array([[0, 3, 2, 1],
       [3, 4, 0, 3],
       [2, 3, 3, 0]])

In [51]:
#using random to generate
arr = np.random.rand(5, 5)
arr

array([[0.28577521, 0.72993507, 0.18435293, 0.6927015 , 0.64607292],
       [0.6084699 , 0.99011195, 0.53915873, 0.4174705 , 0.4456908 ],
       [0.00981425, 0.57125567, 0.83624361, 0.04459741, 0.41409112],
       [0.40508359, 0.35817991, 0.34532643, 0.59996522, 0.16276863],
       [0.2808687 , 0.36522232, 0.2479582 , 0.62340195, 0.72573596]])

In [52]:
arr.shape

(5, 5)

In [53]:
arr.dtype

dtype('float64')

In [54]:
b = np.random.random((5, 5))
b

array([[0.67234758, 0.84197384, 0.53280289, 0.01926649, 0.10473797],
       [0.73093913, 0.82510989, 0.46126527, 0.65051364, 0.93020573],
       [0.86093697, 0.6903386 , 0.56453427, 0.66919336, 0.55074151],
       [0.8488292 , 0.19310993, 0.75177292, 0.29869335, 0.22346751],
       [0.16141524, 0.80061576, 0.05429633, 0.8840859 , 0.57209959]])

In [55]:
b.shape

(5, 5)

In [56]:
b.dtype

dtype('float64')

In [57]:
len(b.shape)

2

In [58]:
b[1:3]

array([[0.73093913, 0.82510989, 0.46126527, 0.65051364, 0.93020573],
       [0.86093697, 0.6903386 , 0.56453427, 0.66919336, 0.55074151]])

In [59]:
#working with comparison operators
arr_int = np.random.randint(5, size=(6, 8))

In [60]:
arr_int

array([[3, 1, 4, 1, 0, 1, 4, 4],
       [0, 0, 3, 0, 4, 4, 2, 3],
       [2, 3, 4, 1, 0, 2, 3, 3],
       [1, 0, 2, 0, 2, 3, 0, 1],
       [0, 4, 3, 0, 3, 3, 3, 4],
       [0, 4, 3, 0, 1, 2, 1, 0]])

In [61]:
arr_int0 =arr_int[0] #taking only first row

In [62]:
arr_int0

array([3, 1, 4, 1, 0, 1, 4, 4])

In [63]:
arr_int0 == 0 #comparing in this row we have 0 or not and

array([False, False, False, False,  True, False, False, False])

In [64]:
arr_int0

array([3, 1, 4, 1, 0, 1, 4, 4])

In [65]:
arr_int0_is012= (arr_int0 == 0) | (arr_int0 == 1) | (arr_int0 == 2) #checking for if there any numbers like 0, 1, 2 {" | " is working as or operator}

In [66]:
arr_int0_is012

array([False,  True, False,  True,  True,  True, False, False])

In [67]:
#Boolean Masking (or Boolean Indexing) in NumPy
arr_int0[arr_int0_is012]

array([1, 1, 0, 1])

In [68]:
arr_int0 == 2

array([False, False, False, False, False, False, False, False])

**Transpose**

Transpose means swapping rows and columns.

In [69]:
marks= [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [70]:
marks[0]

[1, 2, 3, 4]

In [71]:
#think of it like these are marks and subjects, i want math only (in every inner list first element is math marks)\
marks[0][0], marks[1][0], marks[2][0]


(1, 5, 9)

In [73]:
marks

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [76]:
#Transpose without using NumPy

marks_transpose = []
for j in range(len(marks[0])):         #   } this 2 lines creates 4-Empty list
  marks_transpose.append([])           #
  for i in range(len(marks)):          # len(marks) means we have 3 list (think of it like 3 " rows ")
    marks_transpose[j].append(marks[i][j])     # in first iteration {j=0 --> it created first empty list in outer loop and inner loop through 3 times and in first i= 0, marks[i][j]= [0][0]--> is 1 same with in next loop (inner loop) i becomes 1, marks[i][j]= [1][0]-->5, .... like that after completing inner loop iteration (0, 1, 2 {len(marks)= 3}) ...[1, 5, 9] in first created j empty list is fill and next j becomes 1 then same repeats with i 3 iterations --> [2, 6, 10] .....[3, 7, 11], .....[4, 8, 12]
marks_transpose    #return


[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [75]:
for i in marks:
  print(i)

[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]


In [78]:
#using NumPy
marks_array= np.array(marks)    #converting it into numpy array
marks_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
#making transpose\

marks_array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])