<a href="https://colab.research.google.com/github/azeem932356/Numpy-Pandas-OpenCV-DataVisualization-DataScraping/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

short form of Numerical Python

Numpy is written in c

NumPy is originally designed for **CPU** Memory {CPU: Central Processing Unit} and Numpy can't run on **GPU** {GPU has its own Memory called **VRAM**}


In [1]:
#Vectors and Matrices
#Vector is a list of numbers {You can call as 1D Vectors}    --> single digit is called scaler
#Matrics are List of List {You can call as 2D Vectors}

In [2]:
import numpy as np

In [3]:
python_list = [1, 2, 3, 4, 5, -5]
python_list

[1, 2, 3, 4, 5, -5]

In [4]:
#converting a list into a vector
np.array(python_list)

array([ 1,  2,  3,  4,  5, -5])

In [5]:
#checking Dimensions and Shape
numpy_arry = np.array(python_list)
numpy_arry.shape

(6,)

In [6]:
#Dimension
len(numpy_arry.shape)

1

In [7]:
#list of list {2D} Matrix
python_list_list = [[1, 2], [3, 4]]
python_list_list1= np.array(python_list_list)
python_list_list1

array([[1, 2],
       [3, 4]])

In [8]:
python_list_list1.shape

(2, 2)

In [9]:
len(python_list_list1)

2

In [10]:
#Creating list using range()

list(range(5))

[0, 1, 2, 3, 4]

In [11]:
#now using arrange {similar to range function}
np.arange(4)


array([0, 1, 2, 3])

In [12]:
#making shapes zeros and specifying the for 2D zeros(rows, columns)
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [13]:
#zeros for higher dimensions zeros(depth, rows, columns)
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
#you can also do with 1
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [15]:
#using random()

#decimals
np.random.random((2, 2))

array([[0.05705857, 0.13002399],
       [0.25548477, 0.46149446]])

In [16]:
#integers
np.random.randint(1, 10, (2, 3))


array([[1, 8, 8],
       [8, 2, 1]])

In [17]:
#one random integer from(0, 1, 2 3is excluded)
np.random.randint(3)

1

In [18]:
#random size matix
np.random.randint(5, size=(2, 2))

array([[4, 0],
       [2, 3]])

**Data Types - NumPy**


**int** - int8, int16, int36, int64    --> Integers

**uint** - uint8, uint16, uint36, uint64   --> unsigned (nonnegative) integers

**bool** - Bool  --> Boolean (T or F)

**float** - float16, float36, float64, float128   --> floating point numbers

**complex**  - complex64, complex128, complex256    --> complex valued floating-point numbers

**Type**	| **Bits**  | 	**Bytes**	 | **Range**

int8 -->  8 -->    1	-->    -128 to 127

int16	 -->   16	 -->   2	   -->  -32,768 to 32,767

int32	 -->  32	 -->  4	   -->  -2.1 billion to 2.1 billion

int64	 -->  64	-->   8	    -->  ±9.2 quintillion

In [19]:
a = [1, 2, 3, 4]
arr =np.array(a)
arr

array([1, 2, 3, 4])

In [20]:
#to check a data-type
arr.dtype

dtype('int64')

In [21]:
#converting a datatype
b= [1, 2, 3, 4]
arry= np.array(b, dtype= np.int64)
arry.dtype

dtype('int64')

In [22]:
#floating point
a= [1.2, 3.4, 5]
type(a[-1])

int

If you create a NumPy array with mixed data types, NumPy will try to make all elements the same type because NumPy arrays are **homogeneous** (all elements have **one dtype**).

In [23]:
a= np.array([1, 2, 3, "Hello"])  #NumPy array converts all into one data type
print(a)
print(a.dtype)

['1' '2' '3' 'Hello']
<U21


In [24]:
#converting into Integer
a = np.array([1.7, 2.9, 3.1])

b = a.astype(int)

print(b)
print(b.dtype)

[1 2 3]
int64


In [25]:
# a.astype(np.int32).dtype
#                              } ---> explicitly use
 #a.astype(np.int64).dtype

converting to integer truncates the decimal part; it does not **round**

1.7 → 1

2.9 → 2

3.1 → 3

#NumPy - **Slicing**

array[start : stop : step] --> for 1D

arry[rows, columns] --> for 2D

arry[matrix, row, column] ---> for 3D (Tensor)

arry[batch, matrix, row, column]  --> for 4D(Tensor)

**1D** array

In [26]:
a = np.array([10, 20, 30, 40, 50, 60])  #1D

In [27]:
a.shape

(6,)

In [28]:
#for finding dimensions
len(a.shape)

1

In [29]:
#Elements from index 1 to 3
a[1:4]

array([20, 30, 40])

In [30]:
#for single element
a[0]     #--> in 1D array you can access any element by index

np.int64(10)

In [31]:
#you can also use steps also
a[0: 6: 2]

array([10, 30, 50])

**2D** array

arrary[rows, columns]

In [32]:
c= np.random.rand(5, 5) #it give you flot from 0 - 1

In [33]:
c

array([[0.26228149, 0.59029486, 0.41861924, 0.05644373, 0.95406542],
       [0.59644774, 0.01487857, 0.13109414, 0.57210156, 0.3186133 ],
       [0.75391992, 0.37906155, 0.73436009, 0.90346406, 0.58572061],
       [0.24884476, 0.07172484, 0.29124283, 0.07320668, 0.66960244],
       [0.81432516, 0.28552247, 0.6779693 , 0.16763044, 0.40192199]])

In [34]:
d= np.random.randint(5, size=(5, 5))   #it gives you random numbers from 0 - 4 in the shape of (5, 5)

In [35]:
d

array([[3, 4, 0, 4, 1],
       [0, 0, 3, 0, 2],
       [3, 0, 1, 2, 0],
       [1, 0, 4, 4, 0],
       [4, 1, 2, 2, 1]])

In [36]:
d.shape

(5, 5)

In [37]:
len(d.shape)

2

In [38]:
#accessing single element in 2D --> i want first row(0) last element
d[0, 4]

np.int64(1)

In [39]:
#for entire row
d[0,]

array([3, 4, 0, 4, 1])

In [40]:
#first 2 rows
d[0:2, :]

array([[3, 4, 0, 4, 1],
       [0, 0, 3, 0, 2]])

In [41]:
#for last row
d[-1]

array([4, 1, 2, 2, 1])

In [42]:
#entire column
d[:, 4]  #--> read it as rows   ,column

array([1, 2, 0, 0, 1])

In [43]:
#for portion of a 2d
d[0:2, 3:5]

array([[4, 1],
       [0, 2]])

**3D** Array (Tensor)

array[matrix, row, column]

In [44]:
e= np.random.randint(5, size=(2, 3, 4))

In [45]:
e

array([[[4, 1, 4, 4],
        [2, 3, 0, 4],
        [4, 0, 2, 0]],

       [[4, 2, 4, 3],
        [0, 2, 0, 1],
        [1, 1, 0, 1]]])

In [46]:
#shape
e.shape

(2, 3, 4)

In [47]:
#finding Dimension
len(e.shape)

3

In [48]:
#one element
e[0, 1, 2]

np.int64(0)

In [49]:
#entire row
e[0, 1]

array([2, 3, 0, 4])

In [50]:
#first matrix
e[0]

array([[4, 1, 4, 4],
       [2, 3, 0, 4],
       [4, 0, 2, 0]])

In [51]:
#using random to generate
arr = np.random.rand(5, 5)
arr

array([[0.4499816 , 0.06803172, 0.01148152, 0.56758535, 0.74635848],
       [0.21196896, 0.11171376, 0.51525869, 0.41853571, 0.22585254],
       [0.76214342, 0.06789546, 0.69876923, 0.45520558, 0.24668352],
       [0.84039428, 0.14022713, 0.00163111, 0.10118793, 0.79157883],
       [0.32968297, 0.94583884, 0.25463341, 0.97187453, 0.52806996]])

In [52]:
arr.shape

(5, 5)

In [53]:
arr.dtype

dtype('float64')

In [54]:
b = np.random.random((5, 5))
b

array([[0.8019424 , 0.1218495 , 0.34969449, 0.52949701, 0.58164273],
       [0.8874066 , 0.52509937, 0.50730807, 0.31859445, 0.09219816],
       [0.04553381, 0.6733961 , 0.39982231, 0.46086168, 0.58285085],
       [0.84603589, 0.74537878, 0.98096915, 0.31945715, 0.92905967],
       [0.13893691, 0.26690034, 0.39780589, 0.16550738, 0.1352361 ]])

In [55]:
b.shape

(5, 5)

In [56]:
b.dtype

dtype('float64')

In [57]:
len(b.shape)

2

In [58]:
b[1:3]

array([[0.8874066 , 0.52509937, 0.50730807, 0.31859445, 0.09219816],
       [0.04553381, 0.6733961 , 0.39982231, 0.46086168, 0.58285085]])

In [59]:
#working with comparison operators
arr_int = np.random.randint(5, size=(6, 8))

In [60]:
arr_int

array([[0, 3, 4, 4, 0, 1, 2, 1],
       [1, 2, 3, 4, 3, 4, 2, 3],
       [3, 4, 0, 1, 3, 0, 3, 2],
       [4, 4, 4, 1, 1, 2, 2, 2],
       [4, 1, 4, 1, 0, 4, 1, 2],
       [4, 4, 4, 3, 4, 3, 1, 2]])

In [61]:
arr_int0 =arr_int[0] #taking only first row

In [62]:
arr_int0

array([0, 3, 4, 4, 0, 1, 2, 1])

In [63]:
arr_int0 == 0 #comparing in this row we have 0 or not and

array([ True, False, False, False,  True, False, False, False])

In [64]:
arr_int0

array([0, 3, 4, 4, 0, 1, 2, 1])

In [65]:
arr_int0_is012= (arr_int0 == 0) | (arr_int0 == 1) | (arr_int0 == 2) #checking for if there any numbers like 0, 1, 2 {" | " is working as or operator}

In [66]:
arr_int0_is012

array([ True, False, False, False,  True,  True,  True,  True])

In [67]:
#Boolean Masking (or Boolean Indexing) in NumPy
arr_int0[arr_int0_is012]

array([0, 0, 1, 2, 1])

In [68]:
arr_int0 == 2

array([False, False, False, False, False, False,  True, False])

**Transpose**

Transpose means swapping rows and columns.

In [69]:
marks= [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [70]:
marks[0]

[1, 2, 3, 4]

In [71]:
#think of it like these are marks and subjects, i want math only (in every inner list first element is math marks)\
marks[0][0], marks[1][0], marks[2][0]


(1, 5, 9)

In [72]:
marks

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [73]:
#Transpose without using NumPy

marks_transpose = []
for j in range(len(marks[0])):         #   } this 2 lines creates 4-Empty list
  marks_transpose.append([])           #
  for i in range(len(marks)):          # len(marks) means we have 3 list (think of it like 3 " rows ")
    marks_transpose[j].append(marks[i][j])     # in first iteration {j=0 --> it created first empty list in outer loop and inner loop through 3 times and in first i= 0, marks[i][j]= [0][0]--> is 1 same with in next loop (inner loop) i becomes 1, marks[i][j]= [1][0]-->5, .... like that after completing inner loop iteration (0, 1, 2 {len(marks)= 3}) ...[1, 5, 9] in first created j empty list is fill and next j becomes 1 then same repeats with i 3 iterations --> [2, 6, 10] .....[3, 7, 11], .....[4, 8, 12]
marks_transpose    #return


[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [74]:
for i in marks:
  print(i)

[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]


In [75]:
#using NumPy
marks_array= np.array(marks)    #converting it into numpy array
marks_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
#making transpose\

marks_array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [77]:
#calculations using row by row
marks_array.sum(axis=1)

array([10, 26, 42])

In [78]:
#percentage
marks_array.sum(axis=1)/60 *100

array([16.66666667, 43.33333333, 70.        ])

In [79]:
#Broadcasting: Operations on arrays of different dimensions
#using Broadcasting, we can just add vector, and the vector gets Broadcasting/copied so that it can be added

marks

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [80]:
grace_marks= np.array([1, 2, 3])
marks_array + grace_marks          #see this will give you error because we are trying to add 3*4 with 3 it will not happen

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
#using Broadcasting it is possible
#we are converting grace_marks into 2-D matrixs

grace_marks= np.array([[1, 2, 3]]) #--> conveting into 2-D
grace_marks.shape

In [81]:
grace_marks= np.array([[1, 2, 3]]).T   #By suing Transpose we can add
marks_array + grace_marks

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [82]:
weight_list= [0.4, 0.2, 0.2, 0.2]
weight_list

[0.4, 0.2, 0.2, 0.2]

In [83]:
len(weight_list)

4

In [84]:
marks

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [85]:
len(marks)

3

In [87]:
#matix multiplication (@)
A =np.array ([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

B = np.array([
    [0.4],
    [0.2],
    [0.2],
    [0.2]
])

result= A @ B
print(f"Result - 3x1 matrix:\n{result}")

Result - 3x1 matrix:
[[ 2.2]
 [ 6.2]
 [10.2]]


In [88]:
#Tensors
import numpy as np

A = np.array([
    [[1,2],
     [3,4]],

    [[5,6],
     [7,8]]
])

In [89]:
A

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [90]:
A.shape

(2, 2, 2)

In [91]:
A.transpose(0,2,1)

#Keep axis 0 same
#Swap axis 1 and axis 2

array([[[1, 3],
        [2, 4]],

       [[5, 7],
        [6, 8]]])

In [92]:
#NumPy takes less space and memory compared tpo python list

python_list= list(range(100))


In [93]:
python_list[:5]

[0, 1, 2, 3, 4]

In [94]:
#now comparing size
import sys

sys.getsizeof(python_list[0]) * len(python_list)   #taking first element size and multilying it with length of entire list

2800

In [95]:
#now using NUmPy

numpy_array= np.arange(100)
numpy_array[:5]

array([0, 1, 2, 3, 4])

In [96]:
#using built-in fuction and see the difference between Python List and NumPy Array

numpy_array.nbytes

800

In [97]:
l1= [1, 2, 3, 4]
l2= [5, 6, 7, 8]

l3= zip(l1, l2)
tuple(l3)

((1, 5), (2, 6), (3, 7), (4, 8))

In [98]:

#Numpy also take less time to run array compared to Python List

import time

size= 10000000

l1= list(range(10000000))
l2= list(range(10000000))

start_time= time.time()      #recording time
l3= [x+y for x, y in zip(l1, l2)]     #using list comprehension to create a l3 using zip function
end_time= time.time()
print("Python list took,", end_time - start_time)


Python list took, 1.2896928787231445


In [99]:
#Now look for NumPy array

arr1= np.arange(size)
arr2= np.arange(size)

start_time= time.time()
arr3= arr1 + arr2
end_time= time.time()
print("NumPy array took,", end_time - start_time)

NumPy array took, 0.045526981353759766


In [100]:
#Numpy offers best built in fuction use case
#suppose i want to add 2 list
#using python

l4= [1, 2, 3, 4]
l5= [6, 7, 8, 9]

##if i use + for this list it gives concatenate

# l6= l4 + l5
# l6 #[1, 2, 3, 4, 6, 7, 8, 9]

#for addition i need to write for loop, like that to do operations

l6= [x+y for x, y in zip(l4, l5)]
l6

[7, 9, 11, 13]

In [101]:
#using numpy we simple operations to perform any mathematical operations by converting it to Numpy Array

arr4= np.array(l4)
arr5= np.array(l5)

arr6= arr4 + arr5
arr6

array([ 7,  9, 11, 13])

In [106]:
#assingning data-types

numpy_array1= np.array([[10, 23, 40], [10, 45, 67]], dtype= np.float64)
numpy_array1.dtype

dtype('float64')

In [107]:
#linspace() --> Linear Space

# It creates evenly spaced numbers between a start value and an end value.

# Syntax: np.linspace(start, stop, num) -->num= how many numbers you want

a= np.linspace(0, 100, 11)
a

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [101]:
#ravel() and flatten() --> are both converts a multi-dimessional array into a 1-D array

#flatten() --> creates a copy of the original array.

#ravel() --> usually creates a view of the original array, not a copy. "It avoids unnecessary memory copies.", "It is faster.", "Large ML datasets can be several GBs in size."

In [108]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [109]:
#ravel() --> a and b point to same memory

b= a.ravel()
b

array([1, 2, 3, 4, 5, 6])

In [110]:
#flatten() --> it creats copy

c= a.flatten()
c

array([1, 2, 3, 4, 5, 6])

In [111]:
#sum()
a.sum()

np.int64(21)

In [113]:
a.sum(axis=1)

array([ 6, 15])

In [115]:
#matix operations on different regions and countries (rows are products units and columns or regions)

q1= np.array([
    [1, 2, 3],   #product A
    [4, 5, 6],   #product B
    [7, 8, 9]    #product C
])

q2= np.array([
    [10, 20, 30],  #product A
    [40, 50, 60],  #product B
    [70, 80, 90]   #product C
])

In [116]:
#i want to sum all q1 + q2 sales

total_sales= q1 + q2
total_sales

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [117]:
#i want to see difference

q2 - q1

array([[ 9, 18, 27],
       [36, 45, 54],
       [63, 72, 81]])

In [118]:
#for percentage increase

(q2-q1)*100/q1

array([[900., 900., 900.],
       [900., 900., 900.],
       [900., 900., 900.]])

In [120]:
#prices per unit

prices= np.array([
    [10, 20, 30],
    [20, 40, 20],
    [10, 12, 30]
])

q1_revenue= q1 * prices
q1_revenue

array([[ 10,  40,  90],
       [ 80, 200, 120],
       [ 70,  96, 270]])

In [121]:
#we have given discount of 20% in q1, we need to find out how much was it

q1_revenue_discount= q1_revenue *0.2
q1_revenue_discount

array([[ 2. ,  8. , 18. ],
       [16. , 40. , 24. ],
       [14. , 19.2, 54. ]])

In [122]:
#now net revenue

net_revenue= q1_revenue - q1_revenue_discount
net_revenue

array([[  8. ,  32. ,  72. ],
       [ 64. , 160. ,  96. ],
       [ 56. ,  76.8, 216. ]])

In [126]:
#suppose i want to know how much discount we have given across all regions in q1

total_discount_amount_q1= np.sum(q1_revenue_discount)
print(total_discount_amount_q1)

195.2


In [129]:
#np.hstack() -->rows must be same , Horizonatal stack

import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

result = np.hstack((a,b))

print(result)

[1 2 3 4 5 6]


In [130]:
#vstack() --> vertical stack, it joins arrarys one below another(top to bottom)

a = np.array([
    [1,2],
    [3,4]
])

b = np.array([
    [5,6],
    [7,8]
])

result = np.vstack((a,b))

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [131]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [135]:
#hplit() --> Horiznatl split
result = np.hsplit(a, 4)
print(result)

[array([[1],
       [5]]), array([[2],
       [6]]), array([[3],
       [7]]), array([[4],
       [8]])]


In [136]:
x, y= np.hsplit(a, [2])

In [137]:
x

array([[1, 2],
       [5, 6]])

In [138]:
y

array([[3, 4],
       [7, 8]])

In [139]:
#vsplit() --> vertical split

c, v= np.vsplit(a, [1])

In [140]:
c

array([[1, 2, 3, 4]])

In [141]:
v

array([[5, 6, 7, 8]])

In [144]:
#monhly salary

salry= np.array([1, 2, 3, 4])
salry > 1
salry[salry > 1]

array([2, 3, 4])

In [150]:
#argmax() --> Give me the position (index) of the largest value.

#1-D array it gives index
a = np.array([10, 50, 30, 20])

print(a.argmax())

# b= a.argmax()
# a[b]

1
