<a href="https://colab.research.google.com/github/azeem932356/Numpy-Pandas-OpenCV-DataVisualization-DataScraping/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

short form of Numerical Python

Numpy is written in c

NumPy is originally designed for **CPU** Memory {CPU: Central Processing Unit} and Numpy can't run on **GPU** {GPU has its own Memory called **VRAM**}


In [1]:
#Vectors and Matrices
#Vector is a list of numbers {You can call as 1D Vectors}    --> single digit is called scaler
#Matrics are List of List {You can call as 2D Vectors}

In [2]:
import numpy as np

In [3]:
python_list = [1, 2, 3, 4, 5, -5]
python_list

[1, 2, 3, 4, 5, -5]

In [4]:
#converting a list into a vector
np.array(python_list)

array([ 1,  2,  3,  4,  5, -5])

In [5]:
#checking Dimensions and Shape
numpy_arry = np.array(python_list)
numpy_arry.shape

(6,)

In [6]:
#Dimension
len(numpy_arry.shape)

1

In [7]:
#list of list {2D} Matrix
python_list_list = [[1, 2], [3, 4]]
python_list_list1= np.array(python_list_list)
python_list_list1

array([[1, 2],
       [3, 4]])

In [8]:
python_list_list1.shape

(2, 2)

In [9]:
len(python_list_list1)

2

In [10]:
#Creating list using range()

list(range(5))

[0, 1, 2, 3, 4]

In [11]:
#now using arrange {similar to range function}
np.arange(4)


array([0, 1, 2, 3])

In [12]:
#making shapes zeros and specifying the for 2D zeros(rows, columns)
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [13]:
#zeros for higher dimensions zeros(depth, rows, columns)
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
#you can also do with 1
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [15]:
#using random()

#decimals
np.random.random((2, 2))

array([[0.59422504, 0.87249454],
       [0.60014729, 0.58175156]])

In [16]:
#integers
np.random.randint(1, 10, (2, 3))


array([[3, 1, 3],
       [4, 8, 7]])

In [17]:
#one random integer from(0, 1, 2 3is excluded)
np.random.randint(3)

0

In [18]:
#random size matix
np.random.randint(5, size=(2, 2))

array([[2, 1],
       [4, 3]])

**Data Types - NumPy**


**int** - int8, int16, int36, int64    --> Integers

**uint** - uint8, uint16, uint36, uint64   --> unsigned (nonnegative) integers

**bool** - Bool  --> Boolean (T or F)

**float** - float16, float36, float64, float128   --> floating point numbers

**complex**  - complex64, complex128, complex256    --> complex valued floating-point numbers

**Type**	| **Bits**  | 	**Bytes**	 | **Range**

int8 -->  8 -->    1	-->    -128 to 127

int16	 -->   16	 -->   2	   -->  -32,768 to 32,767

int32	 -->  32	 -->  4	   -->  -2.1 billion to 2.1 billion

int64	 -->  64	-->   8	    -->  ±9.2 quintillion

In [19]:
a = [1, 2, 3, 4]
arr =np.array(a)
arr

array([1, 2, 3, 4])

In [20]:
#to check a data-type
arr.dtype

dtype('int64')

In [21]:
#converting a datatype
b= [1, 2, 3, 4]
arry= np.array(b, dtype= np.int64)
arry.dtype

dtype('int64')

In [22]:
#floating point
a= [1.2, 3.4, 5]
type(a[-1])

int

If you create a NumPy array with mixed data types, NumPy will try to make all elements the same type because NumPy arrays are **homogeneous** (all elements have **one dtype**).

In [23]:
a= np.array([1, 2, 3, "Hello"])  #NumPy array converts all into one data type
print(a)
print(a.dtype)

['1' '2' '3' 'Hello']
<U21


In [24]:
#converting into Integer
a = np.array([1.7, 2.9, 3.1])

b = a.astype(int)

print(b)
print(b.dtype)

[1 2 3]
int64


In [25]:
# a.astype(np.int32).dtype
#                              } ---> explicitly use
 #a.astype(np.int64).dtype

converting to integer truncates the decimal part; it does not **round**

1.7 → 1

2.9 → 2

3.1 → 3

#NumPy - **Slicing**

array[start : stop : step] --> for 1D

arry[rows, columns] --> for 2D

arry[matrix, row, column] ---> for 3D (Tensor)

arry[batch, matrix, row, column]  --> for 4D(Tensor)

**1D** array

In [26]:
a = np.array([10, 20, 30, 40, 50, 60])  #1D

In [27]:
a.shape

(6,)

In [28]:
#for finding dimensions
len(a.shape)

1

In [29]:
#Elements from index 1 to 3
a[1:4]

array([20, 30, 40])

In [30]:
#for single element
a[0]     #--> in 1D array you can access any element by index

np.int64(10)

In [31]:
#you can also use steps also
a[0: 6: 2]

array([10, 30, 50])

**2D** array

arrary[rows, columns]

In [32]:
c= np.random.rand(5, 5) #it give you flot from 0 - 1

In [33]:
c

array([[0.78343047, 0.06344859, 0.87723645, 0.7130558 , 0.22178806],
       [0.88595203, 0.89297085, 0.53183434, 0.85179852, 0.52136034],
       [0.6052026 , 0.5064833 , 0.51734694, 0.15974101, 0.19187029],
       [0.62516778, 0.73437416, 0.96850567, 0.06068352, 0.19985134],
       [0.1993655 , 0.92712239, 0.18949806, 0.32277412, 0.87263076]])

In [34]:
d= np.random.randint(5, size=(5, 5))   #it gives you random numbers from 0 - 4 in the shape of (5, 5)

In [35]:
d

array([[1, 4, 3, 0, 3],
       [2, 3, 3, 1, 1],
       [1, 3, 1, 4, 3],
       [1, 2, 3, 0, 3],
       [1, 2, 1, 4, 2]])

In [36]:
d.shape

(5, 5)

In [37]:
len(d.shape)

2

In [38]:
#accessing single element in 2D --> i want first row(0) last element
d[0, 4]

np.int64(3)

In [39]:
#for entire row
d[0,]

array([1, 4, 3, 0, 3])

In [40]:
#first 2 rows
d[0:2, :]

array([[1, 4, 3, 0, 3],
       [2, 3, 3, 1, 1]])

In [41]:
#for last row
d[-1]

array([1, 2, 1, 4, 2])

In [42]:
#entire column
d[:, 4]  #--> read it as rows   ,column

array([3, 1, 3, 3, 2])

In [43]:
#for portion of a 2d
d[0:2, 3:5]

array([[0, 3],
       [1, 1]])

**3D** Array (Tensor)

array[matrix, row, column]

In [44]:
e= np.random.randint(5, size=(2, 3, 4))

In [45]:
e

array([[[1, 2, 2, 4],
        [1, 4, 1, 4],
        [2, 2, 3, 0]],

       [[0, 2, 3, 1],
        [3, 1, 3, 4],
        [2, 2, 4, 2]]])

In [46]:
#shape
e.shape

(2, 3, 4)

In [47]:
#finding Dimension
len(e.shape)

3

In [48]:
#one element
e[0, 1, 2]

np.int64(1)

In [49]:
#entire row
e[0, 1]

array([1, 4, 1, 4])

In [50]:
#first matrix
e[0]

array([[1, 2, 2, 4],
       [1, 4, 1, 4],
       [2, 2, 3, 0]])

In [51]:
#using random to generate
arr = np.random.rand(5, 5)
arr

array([[0.53323953, 0.48362051, 0.94934805, 0.17358213, 0.8752207 ],
       [0.77992377, 0.04608436, 0.17341251, 0.52905647, 0.10290526],
       [0.80871815, 0.78121354, 0.09287891, 0.15389133, 0.96488008],
       [0.82220696, 0.90723415, 0.01849891, 0.51384829, 0.559502  ],
       [0.87312795, 0.9180779 , 0.3799469 , 0.80555502, 0.17896017]])

In [52]:
arr.shape

(5, 5)

In [53]:
arr.dtype

dtype('float64')

In [54]:
b = np.random.random((5, 5))
b

array([[0.31262256, 0.84025661, 0.35579354, 0.16887663, 0.71768715],
       [0.71732171, 0.12049206, 0.6702934 , 0.86133872, 0.01114117],
       [0.16878969, 0.65360173, 0.44061418, 0.14402552, 0.12817018],
       [0.46428296, 0.8224415 , 0.4552914 , 0.0177014 , 0.73495982],
       [0.15919322, 0.38914328, 0.84819948, 0.79412286, 0.84105828]])

In [55]:
b.shape

(5, 5)

In [56]:
b.dtype

dtype('float64')

In [57]:
len(b.shape)

2

In [58]:
b[1:3]

array([[0.71732171, 0.12049206, 0.6702934 , 0.86133872, 0.01114117],
       [0.16878969, 0.65360173, 0.44061418, 0.14402552, 0.12817018]])

In [59]:
#working with comparison operators
arr_int = np.random.randint(5, size=(6, 8))

In [60]:
arr_int

array([[1, 4, 0, 2, 1, 0, 3, 3],
       [0, 1, 2, 3, 2, 2, 2, 0],
       [2, 2, 2, 3, 1, 4, 4, 2],
       [0, 3, 1, 2, 0, 3, 0, 2],
       [0, 2, 4, 1, 2, 2, 2, 4],
       [1, 3, 4, 4, 0, 4, 0, 4]])

In [61]:
arr_int0 =arr_int[0] #taking only first row

In [62]:
arr_int0

array([1, 4, 0, 2, 1, 0, 3, 3])

In [63]:
arr_int0 == 0 #comparing in this row we have 0 or not and

array([False, False,  True, False, False,  True, False, False])

In [64]:
arr_int0

array([1, 4, 0, 2, 1, 0, 3, 3])

In [65]:
arr_int0_is012= (arr_int0 == 0) | (arr_int0 == 1) | (arr_int0 == 2) #checking for if there any numbers like 0, 1, 2 {" | " is working as or operator}

In [66]:
arr_int0_is012

array([ True, False,  True,  True,  True,  True, False, False])

In [67]:
#Boolean Masking (or Boolean Indexing) in NumPy
arr_int0[arr_int0_is012]

array([1, 0, 2, 1, 0])

In [68]:
arr_int0 == 2

array([False, False, False,  True, False, False, False, False])

**Transpose**

Transpose means swapping rows and columns.

In [69]:
marks= [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [70]:
marks[0]

[1, 2, 3, 4]

In [71]:
#think of it like these are marks and subjects, i want math only (in every inner list first element is math marks)\
marks[0][0], marks[1][0], marks[2][0]


(1, 5, 9)

In [72]:
marks

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [73]:
#Transpose without using NumPy

marks_transpose = []
for j in range(len(marks[0])):         #   } this 2 lines creates 4-Empty list
  marks_transpose.append([])           #
  for i in range(len(marks)):          # len(marks) means we have 3 list (think of it like 3 " rows ")
    marks_transpose[j].append(marks[i][j])     # in first iteration {j=0 --> it created first empty list in outer loop and inner loop through 3 times and in first i= 0, marks[i][j]= [0][0]--> is 1 same with in next loop (inner loop) i becomes 1, marks[i][j]= [1][0]-->5, .... like that after completing inner loop iteration (0, 1, 2 {len(marks)= 3}) ...[1, 5, 9] in first created j empty list is fill and next j becomes 1 then same repeats with i 3 iterations --> [2, 6, 10] .....[3, 7, 11], .....[4, 8, 12]
marks_transpose    #return


[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [74]:
for i in marks:
  print(i)

[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]


In [75]:
#using NumPy
marks_array= np.array(marks)    #converting it into numpy array
marks_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
#making transpose\

marks_array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [77]:
#calculations using row by row
marks_array.sum(axis=1)

array([10, 26, 42])

In [78]:
#percentage
marks_array.sum(axis=1)/60 *100

array([16.66666667, 43.33333333, 70.        ])

In [79]:
#Broadcasting: Operations on arrays of different dimensions
#using Broadcasting, we can just add vector, and the vector gets Broadcasting/copied so that it can be added

marks

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [80]:
grace_marks= np.array([1, 2, 3])
marks_array + grace_marks          #see this will give you error because we are trying to add 3*4 with 3 it will not happen

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
#using Broadcasting it is possible
#we are converting grace_marks into 2-D matrixs

grace_marks= np.array([[1, 2, 3]]) #--> conveting into 2-D
grace_marks.shape

In [ ]:
grace_marks= np.array([[1, 2, 3]]).T   #By suing Transpose we can add
marks_array + grace_marks

In [83]:
#matix multiplication (@)
A =np.array ([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

B = np.array([
    [0.4],
    [0.2],
    [0.2],
    [0.2]
])

result= A @ B
print(f"Result - 3x1 matrix:\n{result}")

Result - 3x1 matrix:
[[ 2.2]
 [ 6.2]
 [10.2]]
