<a href="https://colab.research.google.com/github/azeem932356/Numpy-Pandas-OpenCV-DataVisualization-DataScraping/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

short form of Numerical Python

Numpy is written in c

NumPy is originally designed for **CPU** Memory {CPU: Central Processing Unit} and Numpy can't run on **GPU** {GPU has its own Memory called **VRAM**}


In [111]:
#Vectors and Matrices
#Vector is a list of numbers {You can call as 1D Vectors}    --> single digit is called scaler
#Matrics are List of List {You can call as 2D Vectors}

In [112]:
import numpy as np

In [113]:
python_list = [1, 2, 3, 4, 5, -5]
python_list

[1, 2, 3, 4, 5, -5]

In [114]:
#converting a list into a vector
np.array(python_list)

array([ 1,  2,  3,  4,  5, -5])

In [115]:
#checking Dimensions and Shape
numpy_arry = np.array(python_list)
numpy_arry.shape

(6,)

In [116]:
#Dimension
len(numpy_arry.shape)

1

In [117]:
#list of list {2D} Matrix
python_list_list = [[1, 2], [3, 4]]
python_list_list1= np.array(python_list_list)
python_list_list1

array([[1, 2],
       [3, 4]])

In [118]:
python_list_list1.shape

(2, 2)

In [119]:
len(python_list_list1)

2

In [120]:
#Creating list using range()

list(range(5))

[0, 1, 2, 3, 4]

In [121]:
#now using arrange {similar to range function}
np.arange(4)


array([0, 1, 2, 3])

In [122]:
#making shapes zeros and specifying the for 2D zeros(rows, columns)
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [123]:
#zeros for higher dimensions zeros(depth, rows, columns)
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [124]:
#you can also do with 1
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [125]:
#using random()

#decimals
np.random.random((2, 2))

array([[0.8412449 , 0.40419557],
       [0.02842119, 0.48102526]])

In [126]:
#integers
np.random.randint(1, 10, (2, 3))


array([[4, 7, 8],
       [8, 2, 7]])

In [127]:
#one random integer from(0, 1, 2 3is excluded)
np.random.randint(3)

0

In [128]:
#random size matix
np.random.randint(5, size=(2, 2))

array([[4, 4],
       [3, 3]])

**Data Types - NumPy**


**int** - int8, int16, int36, int64    --> Integers

**uint** - uint8, uint16, uint36, uint64   --> unsigned (nonnegative) integers

**bool** - Bool  --> Boolean (T or F)

**float** - float16, float36, float64, float128   --> floating point numbers

**complex**  - complex64, complex128, complex256    --> complex valued floating-point numbers

**Type**	| **Bits**  | 	**Bytes**	 | **Range**

int8 -->  8 -->    1	-->    -128 to 127

int16	 -->   16	 -->   2	   -->  -32,768 to 32,767

int32	 -->  32	 -->  4	   -->  -2.1 billion to 2.1 billion

int64	 -->  64	-->   8	    -->  ±9.2 quintillion

In [129]:
a = [1, 2, 3, 4]
arr =np.array(a)
arr

array([1, 2, 3, 4])

In [130]:
#to check a data-type
arr.dtype

dtype('int64')

In [131]:
#converting a datatype
b= [1, 2, 3, 4]
arry= np.array(b, dtype= np.int64)
arry.dtype

dtype('int64')

In [132]:
#floating point
a= [1.2, 3.4, 5]
type(a[-1])

int

If you create a NumPy array with mixed data types, NumPy will try to make all elements the same type because NumPy arrays are **homogeneous** (all elements have **one dtype**).

In [133]:
a= np.array([1, 2, 3, "Hello"])  #NumPy array converts all into one data type
print(a)
print(a.dtype)

['1' '2' '3' 'Hello']
<U21


In [134]:
#converting into Integer
a = np.array([1.7, 2.9, 3.1])

b = a.astype(int)

print(b)
print(b.dtype)

[1 2 3]
int64


In [135]:
# a.astype(np.int32).dtype
#                              } ---> explicitly use
 #a.astype(np.int64).dtype

converting to integer truncates the decimal part; it does not **round**

1.7 → 1

2.9 → 2

3.1 → 3

#NumPy - **Slicing**

array[start : stop : step] --> for 1D

arry[rows, columns] --> for 2D

arry[matrix, row, column] ---> for 3D (Tensor)

arry[batch, matrix, row, column]  --> for 4D(Tensor)

**1D** array

In [136]:
a = np.array([10, 20, 30, 40, 50, 60])  #1D

In [137]:
a.shape

(6,)

In [138]:
#for finding dimensions
len(a.shape)

1

In [139]:
#Elements from index 1 to 3
a[1:4]

array([20, 30, 40])

In [140]:
#for single element
a[0]     #--> in 1D array you can access any element by index

np.int64(10)

In [141]:
#you can also use steps also
a[0: 6: 2]

array([10, 30, 50])

**2D** array

arrary[rows, columns]

In [142]:
c= np.random.rand(5, 5) #it give you flot from 0 - 1

In [143]:
c

array([[0.22518665, 0.44032842, 0.40782108, 0.68362871, 0.99311728],
       [0.63048543, 0.77420921, 0.33615853, 0.38097354, 0.47544792],
       [0.96431345, 0.87140873, 0.57134054, 0.38797857, 0.75508684],
       [0.24615699, 0.73576698, 0.39722857, 0.63692649, 0.28396864],
       [0.7549155 , 0.1684431 , 0.8551248 , 0.57081535, 0.80167326]])

In [144]:
d= np.random.randint(5, size=(5, 5))   #it gives you random numbers from 0 - 4 in the shape of (5, 5)

In [145]:
d

array([[3, 1, 2, 0, 0],
       [0, 2, 1, 2, 3],
       [2, 2, 1, 3, 2],
       [3, 0, 1, 0, 3],
       [4, 3, 0, 4, 1]])

In [146]:
d.shape

(5, 5)

In [147]:
len(d.shape)

2

In [148]:
#accessing single element in 2D --> i want first row(0) last element
d[0, 4]

np.int64(0)

In [149]:
#for entire row
d[0,]

array([3, 1, 2, 0, 0])

In [150]:
#first 2 rows
d[0:2, :]

array([[3, 1, 2, 0, 0],
       [0, 2, 1, 2, 3]])

In [151]:
#for last row
d[-1]

array([4, 3, 0, 4, 1])

In [152]:
#entire column
d[:, 4]  #--> read it as rows   ,column

array([0, 3, 2, 3, 1])

In [153]:
#for portion of a 2d
d[0:2, 3:5]

array([[0, 0],
       [2, 3]])

**3D** Array (Tensor)

array[matrix, row, column]

In [154]:
e= np.random.randint(5, size=(2, 3, 4))

In [155]:
e

array([[[4, 3, 0, 0],
        [2, 2, 4, 4],
        [2, 3, 0, 3]],

       [[0, 4, 2, 2],
        [0, 0, 0, 4],
        [2, 2, 3, 4]]])

In [156]:
#shape
e.shape

(2, 3, 4)

In [157]:
#finding Dimension
len(e.shape)

3

In [158]:
#one element
e[0, 1, 2]

np.int64(4)

In [159]:
#entire row
e[0, 1]

array([2, 2, 4, 4])

In [160]:
#first matrix
e[0]

array([[4, 3, 0, 0],
       [2, 2, 4, 4],
       [2, 3, 0, 3]])

In [161]:
#using random to generate
arr = np.random.rand(5, 5)
arr

array([[0.58774516, 0.60024222, 0.06722447, 0.7972403 , 0.45987388],
       [0.46419487, 0.42652419, 0.81569204, 0.04266558, 0.78997721],
       [0.60739452, 0.6802591 , 0.63169704, 0.93471427, 0.31399797],
       [0.7360791 , 0.66998274, 0.02318297, 0.53734479, 0.60307781],
       [0.35582238, 0.82618139, 0.14473607, 0.80725501, 0.82358449]])

In [162]:
arr.shape

(5, 5)

In [163]:
arr.dtype

dtype('float64')

In [164]:
b = np.random.random((5, 5))
b

array([[0.6975162 , 0.14723671, 0.28849265, 0.60198279, 0.76625086],
       [0.29648294, 0.02799927, 0.34851534, 0.97211055, 0.43102958],
       [0.43469105, 0.07891125, 0.87508445, 0.45805115, 0.34429401],
       [0.21862489, 0.31483241, 0.40100561, 0.67335097, 0.92353952],
       [0.7392477 , 0.29753854, 0.82644663, 0.2837442 , 0.29221394]])

In [165]:
b.shape

(5, 5)

In [166]:
b.dtype

dtype('float64')

In [167]:
len(b.shape)

2

In [168]:
b[1:3]

array([[0.29648294, 0.02799927, 0.34851534, 0.97211055, 0.43102958],
       [0.43469105, 0.07891125, 0.87508445, 0.45805115, 0.34429401]])

In [169]:
#working with comparison operators
arr_int = np.random.randint(5, size=(6, 8))

In [170]:
arr_int

array([[3, 2, 0, 1, 2, 2, 1, 0],
       [1, 3, 4, 2, 2, 1, 1, 3],
       [1, 2, 3, 3, 4, 2, 1, 4],
       [4, 0, 0, 1, 3, 3, 3, 4],
       [0, 0, 2, 1, 2, 4, 2, 1],
       [1, 1, 1, 2, 3, 2, 4, 2]])

In [171]:
arr_int0 =arr_int[0] #taking only first row

In [172]:
arr_int0

array([3, 2, 0, 1, 2, 2, 1, 0])

In [173]:
arr_int0 == 0 #comparing in this row we have 0 or not and

array([False, False,  True, False, False, False, False,  True])

In [174]:
arr_int0

array([3, 2, 0, 1, 2, 2, 1, 0])

In [175]:
arr_int0_is012= (arr_int0 == 0) | (arr_int0 == 1) | (arr_int0 == 2) #checking for if there any numbers like 0, 1, 2 {" | " is working as or operator}

In [176]:
arr_int0_is012

array([False,  True,  True,  True,  True,  True,  True,  True])

In [177]:
#Boolean Masking (or Boolean Indexing) in NumPy
arr_int0[arr_int0_is012]

array([2, 0, 1, 2, 2, 1, 0])

In [178]:
arr_int0 == 2

array([False,  True, False, False,  True,  True, False, False])

**Transpose**

Transpose means swapping rows and columns.

In [179]:
marks= [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [180]:
marks[0]

[1, 2, 3, 4]

In [181]:
#think of it like these are marks and subjects, i want math only (in every inner list first element is math marks)\
marks[0][0], marks[1][0], marks[2][0]


(1, 5, 9)

In [182]:
marks

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [183]:
#Transpose without using NumPy

marks_transpose = []
for j in range(len(marks[0])):         #   } this 2 lines creates 4-Empty list
  marks_transpose.append([])           #
  for i in range(len(marks)):          # len(marks) means we have 3 list (think of it like 3 " rows ")
    marks_transpose[j].append(marks[i][j])     # in first iteration {j=0 --> it created first empty list in outer loop and inner loop through 3 times and in first i= 0, marks[i][j]= [0][0]--> is 1 same with in next loop (inner loop) i becomes 1, marks[i][j]= [1][0]-->5, .... like that after completing inner loop iteration (0, 1, 2 {len(marks)= 3}) ...[1, 5, 9] in first created j empty list is fill and next j becomes 1 then same repeats with i 3 iterations --> [2, 6, 10] .....[3, 7, 11], .....[4, 8, 12]
marks_transpose    #return


[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [184]:
for i in marks:
  print(i)

[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]


In [185]:
#using NumPy
marks_array= np.array(marks)    #converting it into numpy array
marks_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [186]:
#making transpose\

marks_array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [187]:
#calculations using row by row
marks_array.sum(axis=1)

array([10, 26, 42])

In [188]:
#percentage
marks_array.sum(axis=1)/60 *100

array([16.66666667, 43.33333333, 70.        ])

In [189]:
#Broadcasting: Operations on arrays of different dimensions
#using Broadcasting, we can just add vector, and the vector gets Broadcasting/copied so that it can be added

marks

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [190]:
grace_marks= np.array([1, 2, 3])
marks_array + grace_marks          #see this will give you error because we are trying to add 3*4 with 3 it will not happen

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
#using Broadcasting it is possible
#we are converting grace_marks into 2-D matrixs

grace_marks= np.array([[1, 2, 3]]) #--> conveting into 2-D
grace_marks.shape

In [ ]:
grace_marks= np.array([[1, 2, 3]]).T   #By suing Transpose we can add
marks_array + grace_marks

In [191]:
weight_list= [0.4, 0.2, 0.2, 0.2]
weight_list

[0.4, 0.2, 0.2, 0.2]

In [192]:
len(weight_list)

4

In [197]:
marks

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [198]:
len(marks)

3

In [200]:
#without NumPy matrix multiplication python
result = []

for i in range(len(marks)):
  for j in range(len(weight_list)):
    curr_sum= 0
    for k in range(len(marks[i])):
      curr_sum += marks[i][k] * weight_list[j][k]
    result.append(curr_sum)




TypeError: 'float' object is not subscriptable

In [201]:
results

[]

In [196]:
#matix multiplication (@)
A =np.array ([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

B = np.array([
    [0.4],
    [0.2],
    [0.2],
    [0.2]
])

result= A @ B
print(f"Result - 3x1 matrix:\n{result}")

Result - 3x1 matrix:
[[ 2.2]
 [ 6.2]
 [10.2]]
